apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBBackup
metadata:
  finalizers:
  - percona.com/delete-backup
  name: backup1
spec:
  clusterName: my-cluster-name
  storageName: s3-us-west
#  type: physical
#  compressionType: gzip
#  compressionLevel: 6
#  startingDeadlineSeconds: 300
