apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-name-secrets
type: Opaque
data:
  MONGODB_BACKUP_USER: YmFja3Vw
  MONGODB_BACKUP_PASSWORD: YmFja3VwMTIzNDU2
  MONGODB_CLUSTER_ADMIN_USER: Y2x1c3RlckFkbWlu
  MONGODB_CLUSTER_ADMIN_PASSWORD: Y2x1c3RlckFkbWluMTIzNDU2
  MONGODB_CLUSTER_MONITOR_USER: Y2x1c3Rlck1vbml0b3I=
  MONGODB_CLUSTER_MONITOR_PASSWORD: Y2x1c3Rlck1vbml0b3IxMjM0NTY=
  MONGODB_USER_ADMIN_USER: dXNlckFkbWlu
  MONGODB_USER_ADMIN_PASSWORD: dXNlckFkbWluMTIzNDU2
  PMM_SERVER_USER: cG1tCg==
  PMM_SERVER_PASSWORD: c3VwYXxefHBheno=
